cc_binary(
    name = "acceptance_spec",
    srcs = ["foo_fitnesse_fixture.cpp"],
    #deps = [
    #    "//foo:foo",
    #    "//third_party/fitnesse-cppslim:fitnesse-cppslim"
    #],
    deps = [
        "//foo",
        "@kosta_github_fitnessecppslim//:fitnessecppslim"
    ],
)
